AllCops:
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'config.ru'
    - 'db/**/*'
    - 'Gemfile'
    - 'spec/**/*'
    - 'vendor/**/*'
    - 'spec/spec_helper.rb'
    - 'spec/rails_helper.rb'
  NewCops: enable

require: rubocop-rspec

Style/Documentation:
  Enabled: false

Style/EmptyCaseCondition:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Metrics/AbcSize:
  Max: 40

Metrics/MethodLength:
  Max: 20

Lint/UnusedMethodArgument:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Style/NumberedParameters:
  Enabled: false
