version: '3.8'
services:
  db:
    image: mysql:8.0.23
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - '3308:3306'
    volumes:
      - ./mysqlcnf.d:/etc/mysql/conf.d
      - ./tmp/mysql:/var/lib/mysql
  redis:
    image: redis:6.0.9
    ports:
      - '6380:6379'
  api:
    tty: true
    stdin_open: true
    build: .
    command: tail -f /dev/null #rails s -b 0.0.0.0
    volumes:
      - .:/app
    environment:
      DB_HOST: db
      EDITOR: vim
      BULLET: 1
    ports:
      - "3001:3000"
    depends_on:
      - db
      - redis
  tbls:
    image: k1low/tbls:latest
    volumes:
      - .:/work
    environment:
      TBLS_DSN: mysql://root:@db:3306/app_development
      TBLS_DOC_PATH: docs/tables
    depends_on:
      - db
