# typed: strong
# This is an autogenerated file for Rails' mailers.
# Please rerun bundle exec rake rails_rbi:mailers to regenerate.
class UserMailer
  sig { params(user_id: T.untyped).returns(ActionMailer::MessageDelivery) }
  def self.hello(user_id); end
end
