name: Brakeman

on:
  pull_request:
    paths-ignore:
      - README.md
      - Dockerfile
      - docker-compose.yml
      - 'spec/**'
      - 'docs/**'
  push:
    branches:
      - main
    paths-ignore:
      - README.md
      - Dockerfile
      - docker-compose.yml
      - 'spec/**'
      - 'docs/**'

jobs:
  brakeman:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1.153.0
        with:
          ruby-version: 3.2.2
          bundler-cache: true
      - name: run brakeman
        run: |
          gem install brakeman
          brakeman -6 -A -w 1
