name: Brakeman

on:
  push:
    branches:
      - 'feature/*'
      - main
    paths-ignore:
      - README.md
      - Dockerfile
      - docker-compose.yml
      - 'spec/**'
      - 'docs/**'

jobs:
  brakeman:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1.73.0
        with:
          ruby-version: 3.0.1
          bundler-cache: true
      - name: run brakeman
        run: |
          gem install brakeman
          brakeman -6 -A -w 1
