name: Tbls

on:
  pull_request:
    paths:
      - 'docs/tables/*'
      - 'db/**'
  push:
    branches:
      - main
    paths:
      - 'docs/tables/*'
      - 'db/**'

jobs:
  tbls:
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: development
      DB_HOST: 127.0.0.1
      DB_PORT: 33060
    services:
      db:
        image: mysql:8.0.27
        volumes:
          - mysqlconf.d:/etc/mysql/conf.d
        ports:
          - 33060:3306
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          BIND-ADDRESS: 0.0.0.0
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1.100.1
        with:
          ruby-version: 3.1.0
          bundler-cache: true
      - name: apt-get
        run: |
          sudo apt-get update
          sudo apt-get install libmysqlclient-dev jq
      - name: bundle install
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3 --path vendor/bundle
      - name: migration
        run: |
          bundle exec rails db:create
          bundle exec rails db:migrate
      - name: tbls diff
        uses: docker://k1low/tbls:latest
        env:
          TBLS_DSN: mysql://root:@db:3306/app_development
          TBLS_DOC_PATH: docs/tables
        with:
          args: diff
